name: Installing Python

on: push

jobs:
  py-install:
    runs-on: '${{ matrix.os }}'
      strategy:
        matrix:
          os: [ ubuntu-latest, macos-14, windows-latest ]
    steps:
      - name: install python
        with:
          python.version: [ "3.10", "3.11", "3.12" ]
